### ISSUE TITLE
App crashes after adding flutter_facebook_login 1.2.0

### ISSUE THREAD

**Issue by kaxp** [roughike/flutter_facebook_login#109]
I'm adding facebook login into my app and I have already added facebook login into my 2 previous apps, but this time after adding the plugin my app is crashing immediately I run it and this following error message comes in the console.

Launching lib/main.dart on Moto G 4 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Moto G 4...
Lost connection to device.
Error writing "build/flutter_assets/AssetManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:46577/
Error writing "build/flutter_assets/FontManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:46577/
Error writing "build/flutter_assets/LICENSE" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:46577/
Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:46577/
Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:46577/

And I don't know who's uri, it is.
and I'm trying to add this plugin into a fresh project with version 1.2.0,

I have also adding multiDexEnabled true into my app lvl gradle.
Please help me to solve this problem, Thanks in advance.

**Comment by kaxp** [comment]
So I have run,  flutter clean and my problem got solved.

**Comment by ccfiel** [comment]
I have this problem but it does not solve your solution any ideas?
