### ISSUE TITLE
Question: What is needed to register automatically logged AppEvents in this SDK?

### ISSUE THREAD

**Issue by krossenk** [roughike/flutter_facebook_login#148]
Hi, thank you very much for this great plugin.

I am working for a company that uses Facebook Ads and would like to track automatically logged events inside our Flutter app. Is this possible with this plugin? Or is there another way to achieve what I am asking for.

Link to App Events for Android: https://developers.facebook.com/docs/app-events/getting-started-app-events-android

Sincerely,
Kristian

**Comment by roughike** [comment]
This plugin is only about the login - all other functionality should be in other plugins.
