### ISSUE TITLE
ios (swift) error

### ISSUE THREAD

**Issue by madtocc** [roughike/flutter_facebook_login#15]
Hi, first of all: thanks for your work 👍 Android is working flawlessly. 
However I'm facing an issue when I build the iOS app with swift support.
I guess you can reproduce the error following these steps:
flutter create -i swift first
adding the flutter_facebook_login: 1.1.0 to pubspec.yaml
building the app for iOS (flutter build ios)

returns the following error:
Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/mt/flutterapps/first/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAccessToken.m:21:
    In file included from /Users/mt/flutterapps/first/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.h:19:
    /Users/mt/flutterapps/first/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:24:9: fatal error: 'BridgeAPI/FBSDKBridgeAPIProtocol.h' file not found
    #import "BridgeAPI/FBSDKBridgeAPIProtocol.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

_my current useful flutter doctor -v output:_
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.3 at /Users/mt/Documents/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

do you know any fix or any tip to solve it?
Thank you very much.

**Comment by roughike** [comment]
This issue has been fixed in Flutter with this PR: flutter/flutter#15437

I'm not sure if it's in the beta branch just yet.

You can try [copy-pasting the lines that fix the issue to your ios/Podfile](https://github.com/flutter/flutter/issues/15099#issuecomment-372375566) or [opening your project in XCode and making your plugin headers public](https://groups.google.com/forum/#!msg/flutter-dev/7QRk1RphLDE/5rLS4CciBwAJ)

Closing this issue, since it's not related to this plugin. :)

**Comment by vagrantrobbie** [comment]
I am getting this same error on iOS but only when I am building with --release flag.

I have followed the podfile fixes suggested and that has got me working with development. Do you have any idea why this would throw compile errors with --release?
