### ISSUE TITLE
logInWithReadPermissions not work with other fields

### ISSUE THREAD

**Issue by KaungZawHtet** [roughike/flutter_facebook_login#155]
I tried to get other field permission like this.
FacebookLoginResult result = await facebookLogin
          .logInWithReadPermissions(['user_likes', 'email','public_profile','user_posts']);

I can get those with graph api explorer: https://developers.facebook.com/tools/explorer/
But not work well with this method. How can i be done with it?

**Comment by roughike** [comment]
Read permissions have been deprecated in latest SDK versions. Try `flutter_facebook_login` version 3.0.0 and up - if the issue persists, don't hesitate to file a new one.

**Comment by Zeeshan0201** [comment]
@roughike please update the documentation accordingly...
