### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

### ISSUE THREAD

**Issue by egphp** [roughike/flutter_facebook_login#166]
i received today error , because that plugin 

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

i need to know , can you update it , or have to remove it to

**Comment by roughike** [comment]
3.0.0 uses the latest SDKs and is pushed to Pub. It should solve this issue, but if not, please file another one.

**Comment by w4-sglim** [comment]
This seems not be handled correctly while I have a trouble to install flutter_facebook_login 3.0.0...

**Comment by w4-sglim** [comment]
FYI: I succeeded to install it after uncomment the line
`platform :ios, '9.0'`
