### ISSUE TITLE
why is my page displaying from the half of the screen and not the full screen?

### ISSUE THREAD

**Issue by tonywong1996** [roughike/flutter_facebook_login#17]
when i using Facebook login.
![image](https://user-images.githubusercontent.com/32920112/38477894-fd91122e-3be7-11e8-9ff4-8d2aebd369d4.png)
the main page will down 
![8750ffbafe0710bc41ecfdaad4871f91](https://user-images.githubusercontent.com/32920112/38477901-0a3795de-3be8-11e8-99b5-3b188c54ce34.jpg)
but use the google login ,the main page was full screen

**Comment by roughike** [comment]
There should be a workaround for this in the latest version.

See herr for more context: https://github.com/roughike/flutter_facebook_login/issues/14

**Comment by tonywong1996** [comment]
thx
