### ISSUE TITLE
IOS   flutter_facebook_login: ^1.2.0 BUILD FAILED

### ISSUE THREAD

**Issue by view-man** [roughike/flutter_facebook_login#172]
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target '!ProtoCompiler')
    warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'AMapFoundation')
    warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'Protobuf')
    warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'Flutter')
    warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'WechatOpenSDK')
    Protobuf-aatmvpmdthmmargmncjkjrhaefiq
    /Users/sunyifei/Desktop/ppalarm/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.m:23:9: fatal error: 'Bolts/BFAppLink.h' file not found
    #import <Bolts/BFAppLink.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Runner-aamovkppcruvcdfnhnmhasveylvm
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by view-man** [comment]
help !!!

**Comment by view-man** [comment]
It'ok, my god!

  s.dependency 'FBSDKLoginKit' ,'4.26.0'
  s.dependency 'FBSDKCoreKit' , '4.26.0'

**Comment by roughike** [comment]
Version 1.2.0 is not longer supported. I strongly encourage updating to 3.0.0. Thanks! If you have the same problem with 3.0.0, please file another issue.
