### ISSUE TITLE
Black button appear in the ask before re-login Facebook screen

### ISSUE THREAD

**Issue by khanhnt748** [roughike/flutter_facebook_login#175]
Hi team,
I think something is wrong with this UI when build with **flutter_facebook_login: ^2.0.1**
<img width="401" alt="bug" src="https://user-images.githubusercontent.com/30397729/64698334-e3b1ad80-d4cc-11e9-89c6-952f0348962a.png">
.

**Comment by roughike** [comment]
Should be fixed with 3.0.0 as it uses the latest SDKs. If not, please open another issue.
