### ISSUE TITLE
flutter_facebook_login/facebook login plugin.h file not found 

### ISSUE THREAD

**Issue by lost-vetern** [roughike/flutter_facebook_login#179]
i cloned my project to mac every thing was set as per the documentations. i run "flutter pub get" which was successful and then i opened the project in xcode and when i click run it gives this error 
"flutter_facebook_login/facebook login plugin.h file not found"

**Comment by roughike** [comment]
It's unclear to me if you are trying to run the plugin on a MacOS app? If so, that's unsupported.

If you're having issues on a Flutter iOS app, try to stop the app completely and the rerun. A full restart (not hot reload) is required for plugins to work.

If you're having issues with forking and developing this plugin further, you need to build the iOS project first and open the correct location. For more, see [Using packages](https://flutter.dev/docs/development/packages-and-plugins/using-packages) and [Developing packages & plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages) in official Flutter documentation.

**Comment by maheshmnj** [comment]
I am getting the same  error when trying to build the archive in xcode however I can run the app without any problem on ios and android

**Comment by prashant-v-53** [comment]
I also getting the same error when i run the project with xcode however I can fix the error in ios

**Comment by maheshmnj** [comment]
I had the same issue and this helped me solve it https://github.com/roughike/flutter_facebook_login/issues/220#issuecomment-571454672

**Comment by lost-vetern** [comment]
Okay guys for me the issue was just that the Facebook api was not okay in xcode version less than 10.. So try using the latest version of xcode or either reduce your Facebook plugin version....
