### ISSUE TITLE
Could not pod install for iOS in version 3.0.0.

### ISSUE THREAD

**Issue by edwardmelody** [roughike/flutter_facebook_login#185]
First I can't login with facebook cuz SDK of facebook is too old. I'm going to see an update and read a changelog of this package. I will see a new version 3.0.0. Then I will update to this version and change my code from logInWithReadPermissions to logIn. I will prepare my old code for new version of this package. Finally I'm ready to run for test but it has been crash by **pod install**. It shown as below.

> [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 4.39.1)

>  In Podfile:
    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 5.5)

>You have either:
> * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `flutter_facebook_login`.
   You should run `pod update FBSDKCoreKit` to apply changes you've made.

**Comment by edwardmelody** [comment]
It’s my mistakes. I had clean cache for pod and set iOS platform to 9.0. It will work.

**Comment by premtemp1** [comment]
@edwardmelody 
I am having similar issue and clear the cache. However , I stir get the same issue "Error running pod install"..

Can you please advice how you were able to resolve the issue,,

Thanks

**Comment by edwardmelody** [comment]
> @edwardmelody
> I am having similar issue and clear the cache. However , I still get the same issue "Error running pod install"..
> 
> Can you please advice how you were able to resolve the issue,,
> 
> Thanks

Try follow this step:
1. Run command "flutter clean".
2. Run command "pod cache clean --all"
3. Remove these files and folders "Podfile.lock, .symlinks, Pods"
4. Open Podfile, On the top of file uncomment this line and config minimum iOS platform to 9.0.

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
```

5. Run command "pod repo update"
6. Try to run "pod install" again

Hope this helps. These step it work for me.

**Comment by fbachi** [comment]
@edwardmelody 's solution works!

**Comment by r-sharath** [comment]
The app crashes with this error for me, even after I performed all the steps above
```*** First throw call stack:
(
	0   CoreFoundation                      0x000000011015d02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010ffd5b20 objc_exception_throw + 48
	2   FBSDKCoreKit                        0x000000010af8100f +[FBSDKInternalUtility validateAppID] + 175
	3   FBSDKCoreKit                        0x000000010af811b1 +[FBSDKInternalUtility validateURLSchemes] + 33
	4   FBSDKLoginKit                       0x000000010b0e342e -[FBSDKLoginManager logInParametersWithPermissions:serverConfiguration:] + 110
	5   FBSDKLoginKit                       0x000000010b0e3e6e -[FBSDKLoginManager logIn] + 94
	6   FBSDKLoginKit                       0x000000010b0e3c35 -[FBSDKLoginManager logInWithPermissions:handler:] + 325
	7   FBSDKLoginKit               <…>
Lost connection to device.
``` 

for me

**Comment by Abhishek0116** [comment]
> > @edwardmelody
> > I am having similar issue and clear the cache. However , I still get the same issue "Error running pod install"..
> > Can you please advice how you were able to resolve the issue,,
> > Thanks
> 
> Try follow this step:
> 
> 1. Run command "flutter clean".
> 2. Run command "pod cache clean --all"
> 3. Remove these files and folders "Podfile.lock, .symlinks, Pods"
> 4. Open Podfile, On the top of file uncomment this line and config minimum iOS platform to 9.0.
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '9.0'
> ```
> 
> 1. Run command "pod repo update"
> 2. Try to run "pod install" again
> 
> Hope this helps. The step it work for me.

I have tried all above steps but not worked for me.
