### ISSUE TITLE
error 3.0.0..  logInWithReadPermissions does not exist

### ISSUE THREAD

**Issue by premtemp1** [roughike/flutter_facebook_login#188]
Hello,
  I upgraded from 2.0.0 to 3.0.0 and I getting an error when I am building the app

Error: The method 'logInWithReadPermissions' isn't defined for the class 'FacebookLogin'.

Please let me know how to resolve this issue

Thanks

**Comment by gabrielvictorjs** [comment]
This method has been changed. Try 'logIn'

**Comment by premtemp1** [comment]
Thank you.. I will try it and let you know

**Comment by Armanoide** [comment]
in flutter file, update `logInWithReadPermissions`to `logIn`. I set an example below. 

```
    var facebookLogin = new FacebookLogin();
    List<String> permissions = ["public_profile"];
    var result = await facebookLogin.logIn(permissions);
```

**Comment by premtemp1** [comment]
Thsnkd

**Comment by BenBao93** [comment]
@roughike I ran into the same issue, as the example code is still referencing 'logInWithReadPermissions'. Can this be updated so it is clear the function was renamed?
