### ISSUE TITLE
Unable build pass on iOS - 'flutter_facebook_login/FacebookLoginPlugin.h' file not found

### ISSUE THREAD

**Issue by grand0147** [roughike/flutter_facebook_login#19]
android is build pass and function work normal.
But failed to build pass on iOS caused by 

Lexical or Preprocessor Issue Group
/Users/dereklai/LikeOrDont/ios/Runner/GeneratedPluginRegistrant.m:6:9: 
'flutter_facebook_login/FacebookLoginPlugin.h' file not found

**Comment by grand0147** [comment]
/Users/dereklai/LikeOrDont/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:24:9: fatal error: 'BridgeAPI/FBSDKBridgeAPIProtocol.h' file not found
    #import "BridgeAPI/FBSDKBridgeAPIProtocol.h"

**Comment by jose-granados** [comment]
Same problem.  Followed the Facebook instructions, and even registered  an installation signal in dashboard...but once I add the flutter_facebook_login package, it crashes with this error:  'flutter_facebook_login/FacebookLoginPlugin.h' file not found

**Comment by ilyi1116** [comment]
I think maybe you can run `pod install` to fix this problem
