### ISSUE TITLE
Cocoapods podfile required a higher minimum deployment target

### ISSUE THREAD

**Issue by anthonycic** [roughike/flutter_facebook_login#198]
Hi !

First, thanks for your plugin it really works fine on android.

I use the 3.0.0 version :)

But i can't run my app in IOS...

Here is the error message : 

`Resolving dependencies of Podfile
    [!] CocoaPods could not find compatible versions for pod flutter_facebook_login:
      In Podfile:
        flutter_facebook_login (from .symlinks/plugins/flutter_facebook_login/ios)

Specs satisfying the flutter_facebook_login (from .symlinks/plugins/flutter_facebook_login/ios) dependency were found, but they required a higher minimum deployment target.`

Could you help me please ?

**Comment by anthonycic** [comment]
Also, with your 2.1.0 version i don't have the problem...

**Comment by tuanitpro** [comment]
You can try [194](https://github.com/roughike/flutter_facebook_login/issues/194)

**Comment by anthonycic** [comment]
@tuanitpro ...

Well...

It works fine for me. I do what you told in the 197, i also resolve my flutter doctor issues.
Then it works well.

Thanks a lot man ! Really
