### ISSUE TITLE
Cannot request for graph API scopes

### ISSUE THREAD

**Issue by MisterioRee** [roughike/flutter_facebook_login#199]
With current [example ](https://github.com/roughike/flutter_facebook_login) given for graph 2.12 API may work fine for name profile and email but i need more info e.g birthday, gender and friends etc.
` final result = await facebookSignIn
        .logInWithReadPermissions(["basic_info","email", "user_gender", "user_birthday"]);
   final token = result.accessToken.token;
   `
 
`switch (result.status) {
      case FacebookLoginStatus.loggedIn:
        String grapApi ='https://graph.facebook.com/v4.0/me?fields=id,first_name,last_name,birthday,email,gender,picture&access_token=$token';  `
![image](https://user-images.githubusercontent.com/18234947/66698443-34484080-ecef-11e9-84e7-2dd795f2ede3.png) 

The Token i get in response from Graph API don't have scope for gender

![image](https://user-images.githubusercontent.com/18234947/66698492-999c3180-ecef-11e9-89b8-e7b66c6fabed.png)

The Default token provided by Facebook API debugger:

![image](https://user-images.githubusercontent.com/18234947/66698531-df58fa00-ecef-11e9-9839-b8243530a429.png)

**Comment by adolfdsilva** [comment]
Having the same issue.. did you manage to solve this ?

**Comment by adolfdsilva** [comment]
Ok so after digging a lot... it seems we just cannot get gender, birthday directly. We have to complete app review on facebook.

https://developers.facebook.com/docs/facebook-login/permissions/v2.0#reference-user_gender
