### ISSUE TITLE
FBSDKCoreKit cocoapods issues with latest version 3

### ISSUE THREAD

**Issue by bizz84** [roughike/flutter_facebook_login#201]
After updating my Flutter project to version `3.0.0`, I'm no longer able to build on iOS.

Error:

```
    [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        FBSDKCoreKit (= 4.39.1)
        flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
          FBSDKCoreKit (~> 5.5)
    Specs satisfying the `FBSDKCoreKit (= 4.39.1), FBSDKCoreKit (~> 5.5)` dependency were found, but they required a higher minimum deployment target.
```

This is even with setting a minimum deployment target of 11.0 both in the Podfile, and in the Xcode project settings.

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (3 available)

• No issues found!
```

pod --version is `1.8.3`

Already run `pod repo update` prior to building the app.

None of this is a problem with version `2.x`.

**Comment by Mikkelet** [comment]
have the same problem!

**Comment by diegoveloper** [comment]
I had the same issue and I fixed it with the following steps:

- `flutter clean`
- Remove `ios/Podfile.lock` file
- Go to the `Podfile` file and changed from `platform :ios, '9.0'` to `platform :ios, '11.0'` 
- Go to the terminal , `ios` directory and run `pod install`
- Run the project again.

**Comment by wangbo4020** [comment]
have the same problem!

**Comment by Mikkelet** [comment]
> I had the same issue and I fixed it with the following steps:
> 
> * `flutter clean`
> * Remove `ios/Podfile.lock` file
> * Go to the `Podfile` file and changed from `platform :ios, '9.0'` to `platform :ios, '11.0'`
> * Go to the terminal , `ios` directory and run `pod install`
> * Run the project again.

Im getting 

`[!] CocoaPods could not find compatible versions for pod "flutter_facebook_login":
  In Podfile:
    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)

Specs satisfying the `flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)` dependency were found, but they required a higher minimum deployment target.

`

**Comment by i6x86** [comment]
> I had the same issue and I fixed it with the following steps:
> 
> * `flutter clean`
> * Remove `ios/Podfile.lock` file
> * Go to the `Podfile` file and changed from `platform :ios, '9.0'` to `platform :ios, '11.0'`
> * Go to the terminal , `ios` directory and run `pod install`
> * Run the project again.

In my case I had to run pod update first.

**Comment by MuMiMaNz** [comment]
> I had the same issue and I fixed it with the following steps:
> 
> * `flutter clean`
> * Remove `ios/Podfile.lock` file
> * Go to the `Podfile` file and changed from `platform :ios, '9.0'` to `platform :ios, '11.0'`
> * Go to the terminal , `ios` directory and run `pod install`
> * Run the project again.

In my case, some libs don't support 11.0 and I use 
`platform :ios, '9.0`
then set deployment target in runner.xcsworkspace to 9.0 and it work.

**Comment by eatyours0up** [comment]
I keep running into this issue 

`    ld: library not found for -lFBSDKCoreKit
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build description`

has anyone seen this before? Id really appreciate the help

**Comment by lordmacu** [comment]
i have this problem too

`[!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
  In Podfile:
    FBSDKLoginKit (~> 4.39.1)

    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
      FBSDKLoginKit (~> 5.5)

Specs satisfying the `FBSDKLoginKit (~> 4.39.1), FBSDKLoginKit (~> 5.5)` dependency were found, but they required a higher minimum deployment target.
`

and also put in the Podfile 

` platform :ios, '11.0'`

Please tellme what i need to do thanks

**Comment by bizz84** [comment]
The solution given here works and has been verified:

https://github.com/roughike/flutter_facebook_login/issues/201#issuecomment-543282475

Closing this issue.

**Comment by fannt** [comment]
Hello. I have the same issue as described here but it's happening only on the CI
unfortunately the solution [from here](https://github.com/roughike/flutter_facebook_login/issues/201#issuecomment-543282475) is a manual one and it's not possible on the CI. Any suggestions how to fix that is there more info what's the reason for this issue in a first place? Thanks

**Comment by andreujuanc** [comment]
Hi @fannt  Indeed you are right. But I just managed to build by changing all references in this file /ios/Runner.xcodeproj/project.pbxproj to:
``` 
IPHONEOS_DEPLOYMENT_TARGET = 9.0;
```

I'm not iOS expert, and I cant warranty it would be future proof. But My azure devops pipeline passed the facebook login plugin issue.

**Comment by view-man** [comment]
> I keep running into this issue
> 
> ` ld: library not found for -lFBSDKCoreKit clang: error: linker command failed with exit code 1 (use -v to see invocation) note: Using new build systemnote: Planning buildnote: Constructing build description`
> 
> has anyone seen this before? Id really appreciate the help

are you solve it ？

**Comment by vishwajit76** [comment]
> Hi @fannt Indeed you are right. But I just managed to build by changing all references in this file /ios/Runner.xcodeproj/project.pbxproj to:
> 
> ```
> IPHONEOS_DEPLOYMENT_TARGET = 9.0;
> ```
> 
> I'm not iOS expert, and I cant warranty it would be future proof. But My azure devops pipeline passed the facebook login plugin issue.

thank you

**Comment by mhlulani** [comment]
This is what worked for me:
```bash
flutter clean
rm -f ios/Podfile.lock
cd ios
pod update # updates all the dependencies
cd -

# retry again 
flutter run
```

**Comment by danielehrhardt** [comment]
In my case i had trouble with my M1 Mac. 
I had to start the Terminal with Rosetta and then run 
`pod update`

**Comment by yendiscart** [comment]
> This is what worked for me:
> 
> ```shell
> flutter clean
> rm -f ios/Podfile.lock
> cd ios
> pod update # updates all the dependencies
> cd -
> 
> # retry again 
> flutter run
> ```

Tried all the above and it has not helped.
