### ISSUE TITLE
App crashed after installing flutter_facebook_login Android

### ISSUE THREAD

**Issue by DesortsSolution** [roughike/flutter_facebook_login#215]
I installed flutter_facebook_login after that App crashed on Android but it working in iOS. I'm not able to get crash log.

**Comment by susantstha5** [comment]
> I installed flutter_facebook_login after that App crashed on Android but it working in iOS. I'm not able to get crash log.

hello , i am facing the same problem, did you solve the problem?

**Comment by xalikoutis** [comment]
same here

**Comment by luispalacios270** [comment]
Having the same issue right now, any solution?

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
same here
