### ISSUE TITLE
Can't Find What is wrong

### ISSUE THREAD

**Issue by ericlesMotta** [roughike/flutter_facebook_login#235]
After setting up the envorinment, i try to click on login and app open a webview with the message "Sorry, Something went wrong..." i´ve tested it on multiple devices(two real devices and one Pixel 2  via android studio emulator), and still get the same behavior, one of the devices send a error Failed to atempt login, others send a Cancelled by user.

Anyone has this problem  too? how can i fix it ? 

Android Studio 3.5.3
Android SDK 29.0.2
Flutter V1.12 + hotfix.5

@roughike

**Comment by AlBlanc** [comment]
Same for me 

```
➜ flutter doctor -v 
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G103, locale fr-FR)
    • Flutter version 1.12.13+hotfix.7 at /usr/local/bin/flutter
    • Framework revision 9f5ff2306b (il y a 9 jours), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0
```

**Comment by EmmanuelAmodu** [comment]
Use this same developer account on facebook to login, this should fix it.

**Comment by AlBlanc** [comment]
I faced the same issue and the problem was I was asking permissions `['email', 'default']` (I don't remember from where I copied it).

Permission `default` was the one causing the problem

**Comment by ericlesMotta** [comment]
I got it to work, but in a old version, can´t find a way to get it working on the newest version. 
Downgrade to version 2.0.1, and minor changes in the code itself. Thanks for the Help anyway !
