### ISSUE TITLE
plugin crashes the app

### ISSUE THREAD

**Issue by ZaynJarvis** [roughike/flutter_facebook_login#24]
after adding plugin "flutter_facebook_login: ^1.1.1" or "flutter_facebook_login: ^1.1.1",
fail to build the apk, causing an immediate exit when open the app.

Built build/app/outputs/apk/debug/app-debug.apk.

after this step, nothing comes out.

**Comment by roughike** [comment]
Did you remember to follow these installation instructions in the README? 

https://github.com/roughike/flutter_facebook_login/tree/bugfix/resolve-ios-build-issues#installation

If you didn't touch your AndroidManifest.xml, it will result in a crash.

**Comment by ZaynJarvis** [comment]
Oh, Thank you. I will try it later.

**Comment by roughike** [comment]
Closing due to not getting a response, and due to fact that not following the installation instructions was the case for another user having the same issue :)

Feel free to comment if the problem persists.

**Comment by Echani** [comment]
It would be nice if those additional installation instructions were found here.
https://pub.dartlang.org/packages/flutter_facebook_login#-installing-tab-

**Comment by roughike** [comment]
That is something I can't change - pub doesn't allow customizing that section for package maintainers.

**Comment by timoteo7** [comment]
In android/gradle.properties i added:
```
android.useAndroidX=true
android.enableJetifier=true
```

and stop to crash...
