### ISSUE TITLE
FacebookSDK or CocoaPods for ios?

### ISSUE THREAD

**Issue by matejthetree** [roughike/flutter_facebook_login#25]
Hello,

which one to use when setting the app for iOS

asked here as well 
https://stackoverflow.com/questions/50634576/setting-up-facebook-app-for-ios-in-flutter-with-cocoapods-or-facebooksdk

**Comment by roughike** [comment]
Use pub.

https://pub.dartlang.org/packages/flutter_facebook_login#-installing-tab-
