### ISSUE TITLE
Facebook not login with install facebook app in flutter

### ISSUE THREAD

**Issue by harithany** [roughike/flutter_facebook_login#254]
I had installed a Facebook login in my flutter app . and everything alright. but when install Facebook app. login square show and when press login nothing does and not log in. why?

**Comment by AlanChaves** [comment]
Também estou tendo o mesmo problema, só funciona como web.

**Comment by Jenry94** [comment]
same issue

**Comment by smocken78** [comment]
i just tested this usecase on iOS device and the login works fine.
Is this error occuring on android devices or on iOS devices as well?

I am curious because i received an email from facebook, complaining about a non working login.

**Comment by AlanChaves** [comment]
Você tem que vincular sua conta do Facebook na conta de desenvolvedor no
console do Facebook e depois o hash da sua aplicação e funciona.

Obrigado.

Em dom, 29 de mar de 2020 19:05, smocken78 <notifications@github.com>
escreveu:

**Comment by danilof** [comment]
Same issue here. Not working on android. Please fix this - we need to publish our app and this is must have.

**Comment by danilof** [comment]
I found work round - redirect to FB web view like this:
final facebookSignIn = FacebookLogin();
facebookSignIn.loginBehavior = FacebookLoginBehavior.webOnly;
...
Now it works!

**Comment by gianlucainnocente** [comment]
Same problem. On ios it uses Webview, and it is ok.
But on android it doesn't use the installed Facebook app.

**Comment by Kiruel** [comment]
@danilof Your workarround works. Btw, this error appear when I have the Facebook app installed to my device and I'm login to it.

![image0](https://user-images.githubusercontent.com/8250175/79221346-eb1ba980-7e55-11ea-8000-47b72edfebdd.jpg)

**Comment by gianlucainnocente** [comment]
Same problem :(

**Comment by vksBhardwaj** [comment]
hi Guys i solved this problem You need to get Key hash From SHA-1 Key and all working fine

**Comment by buidan** [comment]
For iOS, I found a working solution by add some extra code to AppDelegate.swift
```
override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
         if url.scheme == "fbXXXXXXXXX" {
                return ApplicationDelegate.shared.application(app, open: url, options: options)
         }
        .....
    }
```

Relace XXXXXXXXX with your facebook ID

**Comment by RathaIct** [comment]
**Edit AppDelegate.swift**


------


```
import FBSDKCoreKit

override func application(_ application: UIApplication, open url: URL,
                                    options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
            if url.scheme == "fbXXXXXXXXXXXXXX" {
                return ApplicationDelegate.shared.application(application,open:url,options:options)
             }
          .....
}
```

**Comment by darmawan01** [comment]
Is there any update for this issues on android/ios ?

**Comment by riteshmj** [comment]
Facing same issue. Is there any update on this?

**Comment by abdulhannan123** [comment]
> I am unable to use :
final facebookSignIn = FacebookLogin();
facebookSignIn.loginBehavior = FacebookLoginBehavior.webOnly;

Help will be highly appreciated. Thanks!

![image](https://user-images.githubusercontent.com/89992873/150926048-754ac0aa-052e-4e2b-982f-b5ea51a9b9cc.png)
![D665A399-BD30-45E0-B095-FADF9CEBF868](https://user-images.githubusercontent.com/89992873/150927531-785d86a9-e9b6-4fa1-a37c-7de48ea7f539.jpg)

**Comment by tiagoon** [comment]
Esta resposta resolveu meu problema por aqui: https://stackoverflow.com/a/54685070/13649080

> Download your APK to your PC in java jdk\bin folder
> 
> in my case C:\Program Files\Java\jdk1.7.0_121\bin
> 
> Go to java jdk\bin folder and run cmd then copy the following command in your cmd
> 
> keytool -list -printcert -jarfile yourapkname.apk
> Copy the SHA1 value to your clipboard like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84 and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64. This is what Facebook requires get the generated hash ********************= and copy the key hash to the facebook app.

**Comment by colorwu76** [comment]
i got the same issue,try many times.
finally i generate a release-apk,then it work
may be its relate to security or something ，idk

**Comment by colorwu76** [comment]
i got the same issue,try many times.
finally i generate a release-apk  , add the release-apk's key hashes to the facebook app, then it work
may be its relate to security or something ，idk
