### ISSUE TITLE
How to get refresh token as well in result

### ISSUE THREAD

**Issue by dkansh** [roughike/flutter_facebook_login#263]
Can we get the refresh token as well in the result? I need to call Facebook graph API several time in application and the access token get expired very soon. So need refresh token to refresh the access token.

**Comment by ncpleslie** [comment]
You can exchange a short-lived token (Few hours) with a long-lived token (60 days). flutter_facebook_login should give you a long-lived token (60 days), but if it doesn't you can follow this guide by Facebook to exchange your token with a long-lived token.

https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing/

**Comment by dkansh** [comment]
Hey @ncpleslie ,

Thanks for the reply. I when through your given link and for now my issue is solved. But still, I feel that it's good to have feature is refresh token is also returned by this plugin.

**Comment by cubuspl42** [comment]
@dkansh How did the link help you? Did you actually receive a short-lived token from `flutter_facebook_login`? It shouldn't be possible, if I understand correctly.

**Comment by cubuspl42** [comment]
I've created a new issue related to token refreshing. See https://github.com/roughike/flutter_facebook_login/issues/289.
