### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by vedangdate** [roughike/flutter_facebook_login#280]
I am not seeing any changes to the library even after it says that the build is failing on pub.dev
Is this normal?
Is anyone maintaining this thing?
Am I missing something while implementing this? (Is this working for people with newest versions)

https://medium.com/@karlwhiteprivate/flutter-facebook-sign-in-with-firebase-in-2020-66556a8c3586
Any explanation for this?

**Comment by cleanu** [comment]
https://medium.com/@karlwhiteprivate/flutter-facebook-sign-in-with-firebase-in-2020-66556a8c3586
this library is deprecated
