### ISSUE TITLE
Facebook SDK v9?

### ISSUE THREAD

**Issue by vixez** [roughike/flutter_facebook_login#305]
I got an email from Facebook that the current SDK is no longer supported, and some of my apps have been upgraded to v9.0.

Is support for Facebook SDK v9 planned?

**Comment by JonataCSantos** [comment]
I'm waiting for an answer for this too

**Comment by shinriyo** [comment]
until 2023/1/20

**Comment by shinriyo** [comment]
@oughike
is it difficult?

**Comment by danielgomezrico** [comment]
@shinriyo made a typo on the ping so I decided to put it right @roughike, any thoughts on this?

**Comment by danielgomezrico** [comment]
Links:
- [Facebook SDK 9 changes](https://developers.facebook.com/blog/post/2021/01/19/introducing-facebook-platform-sdk-version-9/)
- [Android SDK Changes](https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md?fbclid=IwAR2jtiwMPFAYjnYL6lZDlChxE9w7suzh98dIa5VY8BQRdJhTN4JbvUqXh2o)
- [iOS SDK Changes](https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md?fbclid=IwAR2V7E7kgxIzMi8grt9pEKzL-90PyU5ahS7NeQpWDIsGuWPHbwNFii3Svks)

**Comment by vixez** [comment]
I switched to [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth), it was a minimal effort to replace this package. Seems to work fine, and has web support (that I have yet to test).

**Comment by M001T** [comment]
I hope the author updates quickly ...

**Comment by darwin-morocho** [comment]
This plugin is obsolete. You don't have any updates since september 2019

**Comment by vixez** [comment]
I will close this, as it seems to be obsolete indeed.

**Comment by shinriyo** [comment]
@vixez 
Thank you for your indicate recommended other plugin.
