### ISSUE TITLE
Google sign in not working when i add this plugin flutter_facebook_login: ^2.0.1

### ISSUE THREAD

**Issue by srinivasPaidisetti** [roughike/flutter_facebook_login#306]
this below error I'm getting 
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

if I remove this flutter_facebook_login: ^2.0.1 plugin Google sign-in works fine

Please help me, Thanks

**Comment by darwin-morocho** [comment]
This plugin is obsolete. You don't have any updates since september 2019

**Comment by darwin-morocho** [comment]
> this below error I'm getting
> MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
> 
> if I remove this flutter_facebook_login: ^2.0.1 plugin Google sign-in works fine
> 
> Please help me, Thanks

This plugin is obsolete. You don't have any updates since september 2019. 

Also before run your app you need to configure the Facebook sdk on Android and iOS if you don't do it you will have that error because the Facebook sdk will try to find the configuration
