### ISSUE TITLE
Facebook initialized error

### ISSUE THREAD

**Issue by ntsdev** [roughike/flutter_facebook_login#36]
Hi Roughike,

I am getting this error when I try to run the app i had pasted same as you done

The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

**Comment by trieutritam** [comment]
Hi,
Please make sure you add below config inside:
<application ...>
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

...
</application>

**Comment by roughike** [comment]
This happens if you have not set the facebook app id properly. Follow the README instructions.
