### ISSUE TITLE
Native mode not working

### ISSUE THREAD

**Issue by nextifyy** [roughike/flutter_facebook_login#37]
Hey, i want to use "native only" method when user is logging in.
But when im testing signing in, webview is showing anyway even if i have facebook app installed.

`facebookSignIn.loginBehavior = FacebookLoginBehavior.nativeOnly;`

Isn't working too, i always see this ugly webview screen >.<

Thanks for help.

**Comment by roughike** [comment]
Make sure that you set the login behavior before calling `loginWithReadPermissions`.
