### ISSUE TITLE
Relogin on Android is considered cancelled by user

### ISSUE THREAD

**Issue by deckerst** [roughike/flutter_facebook_login#38]
On Android, connecting to Facebook once works fine but following attempts fail. So it fails when the facebook activity remembers the credentials, skips the prompt and only displays the confirmation screen. flutter_facebook_login fails by reporting a "cancelledByUser" status instead of "loggedIn".

On iOS, everything works great, whether credentials are prompted or not.

I've tested this on an emulator running on Android 9.0, and on a real device on 7.1.1. Neither of these have the Facebook app installed.

I'm using flutter_facebook_login 1.1.1.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (4 available)

**Comment by hnvn** [comment]
I confirmed this

**Comment by VictorCamargo** [comment]
Same here. I solved that by logout user before login.

```
// Logout user before login
await facebookSignIn.logOut();

var result = await facebookSignIn.logInWithReadPermissions(['email']);
```

**Comment by roughike** [comment]
You should not trigger the `logInWithReadPermissions` (or `loginWithPublishPermissions`) multiple times:

* when the login is in progress, you should disable your facebook login button
* if the user is logged in, there shouldn't be a way to trigger the login again
* when the user logs out of your app, you should probably call `logout()` on the Facebook Login plugin.

If above is not possible, before calling the login methods, you could do something like this:

```dart
final existingToken = await facebookLogin.currentAccessToken;

if (existingToken != null) {
  // Reuse existing access token, no need to sign in just now
} else {
  // Not logged in yet
  facebookLogin.logInWithReadPermissions(['email']);
}
```
