### ISSUE TITLE
Store Kit errors in iOS Build

### ISSUE THREAD

**Issue by CharlesCleveJr** [roughike/flutter_facebook_login#39]
![screen shot 2018-08-26 at 2 14 09 pm](https://user-images.githubusercontent.com/13074429/44632092-93f05a80-a93a-11e8-90c1-258276142cae.png)
I'm getting the above SK error in my iOS Build.  Any ideas on how to fix these?

**Comment by roughike** [comment]
This should not be related with this plugin.
