### ISSUE TITLE
Programatically setting facebook app id

### ISSUE THREAD

**Issue by kaetemi** [roughike/flutter_facebook_login#41]
Any mechanism to set the app id programmatically? We're loading our app configuration dynamically on start up to accommodate separate testing environments.

**Comment by roughike** [comment]
This is not supported by the Facebook SDK, as there's no way to set the scheme programmatically.

**Comment by kaetemi** [comment]
Does `setApplicationId` not work for this purpose?

https://developers.facebook.com/docs/reference/android/current/class/FacebookSdk/

**Comment by kaetemi** [comment]
Alternatively, any way to fetch them from the plugin, so we can double check easily that they match the one expected?

**Comment by roughike** [comment]
Hey, do you mind creating a new issue about that?

**Comment by kaetemi** [comment]
Will do.
