### ISSUE TITLE
Error on login again 

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [roughike/flutter_facebook_login#42]
Hello if i log in for first time, there is no error then i log out, but when i want to log in again it gives me this error "line 3734 pos 12 _state._elemnt == null is not true"

**Comment by roughike** [comment]
Closing this one as I'm not sure if reproduces at this point and I don't want to keep it hanging around if I don't have concrete plans on debugging it. Feel free to comment if you encounter this one again and I'll reopen.
