### ISSUE TITLE
Can I get more than just first name, last name, picture and id?

### ISSUE THREAD

**Issue by fmmalta** [roughike/flutter_facebook_login#43]
Hi, I implemented your plugin, everything is working fine, but I want to extract more data from the graph url. Me and my friend, we both tried to edit the graph url adding some scopes like birthday, gender, location... but no success. Is there a way to get this extra data?

**Comment by roughike** [comment]
This plugin only handles the login for you, hence the name `flutter_facebook_login`. See the Facebook Graph API documentation for other use cases.
