### ISSUE TITLE
errorMessage: Unsupported get request. Object with ID 'xxxxxx' does not exist, cannot be loaded due to missing permissions,

### ISSUE THREAD

**Issue by KeshavAdityaRP** [roughike/flutter_facebook_login#44]
E/GraphResponse( 3033): {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID 'xxxxxx' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}

**Comment by rakeshlanjewarwork** [comment]
I am Having Same Issue !

**Comment by roughike** [comment]
Not related to this plugin, see: https://stackoverflow.com/a/20959339/940036
