### ISSUE TITLE
unable to launch on iOS

### ISSUE THREAD

**Issue by manujbahl** [roughike/flutter_facebook_login#5]
Below is the output from flutter run

$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                0.7s
CocoaPods' output:
↳
    Generated.xcconfig must exist. If you're running pod install manually, make sure flutter build or flutter run is executed once first.
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`arm64`)
    
    Finding Podfile changes
      R Flutter
      M flutter_facebook_login
    
    Fetching external sources
    -> Fetching podspec for `flutter_facebook_login` from `/Users/MBahl/flutter/projects/flutter_facebook_login-master/ios`
    
    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `Flutter` depended upon by `flutter_facebook_login`
    
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:381:in `find_cached_set'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:351:in `specifications_for_dependency'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:156:in `search_for'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:267:in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:260:in `each'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:260:in `sort_by'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:260:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/molinillo-0.6.4/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:110:in `resolve'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:770:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:767:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone X.

**Comment by roughike** [comment]
A case of "works on my machine".

Couple things:
* this project uses the Gradle 4.1 plugin and Android Studio 3.0 setup. When did you create your project? Have you [migrated into the new project template](https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1)?
* which version of `flutter_facebook_login` are you using? **1.0.0** didn't work with iOS at all.
* which version of Flutter are you using? (run `flutter --version` in terminal)
* does it work with a completely fresh new project on your machine?

**Comment by manujbahl** [comment]
FIXED ... Thanks.
everything was good except that my flutter was an older version. Upgrading flutter to the latest fixed the issue.

**Comment by roughike** [comment]
Awesome!
