### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri

### ISSUE THREAD

**Issue by prashantrahate** [roughike/flutter_facebook_login#53]
**"Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri"**  this is what i am getting after adding your plugin in my flutter application.

I tried with version 1.1.1, 1.1.0 and 1.0.3 of your plugin got the same issue. I already tried searching on internet regarding this problem but no any satisfactory answer found.

**Comment by docaohuynh** [comment]
I had same problem how do you solve it

**Comment by ccfiel** [comment]
any idea how did you solve this problem?

**Comment by ccfiel** [comment]
I have solve this problem by following this steps.

Once you have the Facebook App ID figured out, youll have to do two things.

First, copy-paste the following to your strings resource file. If you don't have one, just create it.

**\<your project root\>/android/app/src/main/res/values/strings.xml**

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Your App Name here.</string>

    <!-- Replace "000000000000" with your Facebook App ID here. -->
    <string name="facebook_app_id">000000000000</string>

    <!--
      Replace "000000000000" with your Facebook App ID here.
      **NOTE**: The scheme needs to start with `fb` and then your ID.
    -->
    <string name="fb_login_protocol_scheme">fb000000000000</string>
</resources>
```

Then you'll just have to copy-paste the following to your _Android Manifest_:

**\<your project root\>/android/app/src/main/AndroidManifest.xml**

```xml
<meta-data android:name="com.facebook.sdk.ApplicationId"
    android:value="@string/facebook_app_id"/>

<activity android:name="com.facebook.FacebookActivity"
    android:configChanges=
            "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
    android:label="@string/app_name" />

<activity
    android:name="com.facebook.CustomTabActivity"
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="@string/fb_login_protocol_scheme" />
    </intent-filter>
</activity>
```
