### ISSUE TITLE
Domain=com.facebook.sdk.core Code=3

### ISSUE THREAD

**Issue by quetool** [roughike/flutter_facebook_login#58]
Hi, I am getting this error on iOS

`
Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}
`

**Comment by quetool** [comment]
Ok, the problem is version 4.39 FBSDKLoginKit and FBSDKCoreKit.
Two things:
1. If you set your Podfile like `'FBSDKLoginKit' '~> 4.32'` it will install latest versión (4.39) because of the `~>` and version is buggy, so, maybe you can set your Podfile to install a fixed particular version below 4.39 like `'FBSDKLoginKit' '~> 4.38'`.

2. The problema by doing this is that no matter what, it will install `FBSDKCoreKit 4.39` (the buggy version) so I had to edit my Podfile.lock manually by changing occurrences of 4.39 with 4.38 and now it is working.

I forked your repo awaiting you (or facebook) to fix it

This is now the podspec
https://github.com/quetool/flutter_facebook_login/blob/master/ios/flutter_facebook_login.podspec
But like I said, no matter this install FBSDKLoginKit 4.38 it's still installing FBSDKCoreKit 4.39, so you have to manually edit the Podfile.lock and then run pod install 
So Podfile.lock remain like this

```
PODS:
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - FBSDKCoreKit (4.38.0):
    - Bolts (~> 1.9)
  - FBSDKLoginKit (4.38.0):
    - FBSDKCoreKit

```

**Comment by scarabele** [comment]
Also has the same problem

**Comment by quetool** [comment]
@scarabele can you please do what I am saying in the comment above? In order to check if it is the correct fix? I think just editing your Podfile.lock like that and doing `pod install` should fix it

**Comment by quetool** [comment]
@scarabele i am still getting an error with 4.38.0 but this time is "error 308" and it is not always, appear to be just random (?)
I think I will go back to 4.32 and check there are no bugs there...

**Comment by scarabele** [comment]
Can you show us your info.plist?

**Comment by quetool** [comment]
Hi @scarabele, the problem isn't my Info.plist, it is not the first time I work with facebook sdk. The problem seems to be with the facebook sdk itself 
https://github.com/facebook/facebook-swift-sdk/issues/286#issuecomment-433700139

**Comment by quetool** [comment]
Here it is the hotfix... https://github.com/facebook/facebook-objc-sdk/pull/922/files
