### ISSUE TITLE
CONNECTION_FAILURE: TigonError(3): GraphQLHttpFailureDomain(401) HTTP Error 

### ISSUE THREAD

**Issue by vu111293** [roughike/flutter_facebook_login#60]
I cached error case when call 
final FacebookLoginResult result = await facebookSignIn.logInWithReadPermissions(['email']);

    switch (result.status) {
      case FacebookLoginStatus.error:
....
     }

Enviroment:
+ Facebook app installed (logged in status)
+ Lib: flutter_facebook_login: ^1.1.1
+ Flutter version
Flutter 0.11.9 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d48e6e433c (3 weeks ago) • 2018-11-20 22:05:23 -0500
Engine • revision 5c8147450d
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Please help me check it.

**Comment by roughike** [comment]
This happens when your phone doesn't have internet connection, not really related to this plugin.
