### ISSUE TITLE
Error adding facebook activity to manifest

### ISSUE THREAD

**Issue by Arthur-Kamau** [roughike/flutter_facebook_login#61]
i get this error when editing my path_to_flutter_app/android/app/src/main/AndroidManifext.xml
What could be the cause of the errror
``
![screenshot from 2018-12-13 18-01-58](https://user-images.githubusercontent.com/30284230/49947167-9be00480-ff01-11e8-8d5a-7b470a4b0e04.png)

here is my flutter doctor -v

![screenshot from 2018-12-13 18-02-31](https://user-images.githubusercontent.com/30284230/49947323-009b5f00-ff02-11e8-9395-5729977fda99.png)

here is the data appended to my manifest file

![screenshot from 2018-12-13 18-04-01](https://user-images.githubusercontent.com/30284230/49947365-1c9f0080-ff02-11e8-9068-8b25e83e3968.png)

Whats causing the error.

**Comment by pedrohenriquerls** [comment]
I get the same error too, even if I remove all the facebook config 🤔 
I am using the flutter 1.0.0

**Comment by roughike** [comment]
You didn't follow the README - in your case, you're missing the appropriate string resource. Setup your app with Facebook and follow the README instructions.
