### ISSUE TITLE
Forgive me for not running.

### ISSUE THREAD

**Issue by ThinOfSnowDance** [roughike/flutter_facebook_login#67]
E/flutter ( 6138): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6138): MissingPluginException(No implementation found for method loginWithReadPermissions on channel com.roughike/flutter_facebook_login)
I QUIT

**Comment by roughike** [comment]
I'm guessing you didn't stop your Flutter app entirely, but did a hot restart / hot reload after adding the plugin. The solution is to do a full restart.
