### ISSUE TITLE
Is there a way to dynamically set the App ID fo facebook login?

### ISSUE THREAD

**Issue by manujbahl** [roughike/flutter_facebook_login#8]
Is there a way to dynamically set the App ID fo facebook login?

Both iOS and Android provide a way to explicitly set the app id.
Android has  FacebookSdk.setApplicationId(ACTIVE_APP_ID); 
and iOS has [FBSDKSettings setAppID:ACTIVE_APP_ID];

How can I accomplish that via this plugin for flutter?

**Comment by manujbahl** [comment]
If you add that ability .. there is also displayName   
(void)setDisplayName:(NSString *)displayName;

for iOS as an example these methods are all defined in ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKSettings.h

**Comment by roughike** [comment]
Thanks for the suggestion, I'll look into it!

**Comment by manujbahl** [comment]
Thanks... I can also try and look into it. Any pointers on how I can help?

**Comment by roughike** [comment]
Sure! 

If you want to do a PR, look into [the twitter login plugin for ideas](https://github.com/roughike/flutter_twitter_login/blob/master/lib/flutter_twitter_login.dart). 

The general idea is to construct an instance of the `FacebookLogin` with the `app_id` and cache it in the Dart side. 

Then with every method call, you basically pass the same `app_id` to the native side, along with other things the specific method needs. This is just to reduce roundtrips and avoiding any async/await with the construction of the `FacebookLogin` instance.

In the native side, you just simply initialize the Facebook Login SDK with the `app_id` you get from Dart side. If the initialization is already done, you just ignore it and return the already initialized client. [See the twitter login for a general idea](https://github.com/roughike/flutter_twitter_login/blob/master/android/src/main/java/com/roughike/fluttertwitterlogin/fluttertwitterlogin/TwitterLoginPlugin.java#L91-L100).

Just shoot me with a PR even if it's incomplete and I'll help. :)

**Comment by roughike** [comment]
@manujbahl I think I'm going to take a look soon, but don't want to do unneeded work if you're already doing something. Are your working on something here, or is it okay for me to take over?

**Comment by manujbahl** [comment]
I have not had a chance to work on it yet. Please go ahead and take it over.

Thanks
- Manuj
_____________________________

**Comment by roughike** [comment]
I looked into this in detail just now, and correct me if I'm wrong, but seems like getting rid of the AndroidManifest and Info.plist configuration isn't possible.

While there's a way of setting the app id dynamically, the scheme still needs to be set in AndroidManifest and Info.plist. Intent Filters on Android don't support dynamic setup, and it's a crucial part of the Facebook login process in the case where the user doesn't have the official native Facebook app installed.

The [official react native FBSDK from Facebook](https://github.com/facebook/react-native-fbsdk) requiring some Android & iOS specific configuration also seems to support that this kind of thing can't be done.

Feel free to comment if you find me being wrong, and I'll be happy to reopen!

**Comment by manujbahl** [comment]
I'm not totally trying to get rid of the plist and manifest files. Only to have the app is set dynamically via the FBSDKSettings class. Anyway to just expose access to the setAppID method.

- Manuj
________________________________
