### ISSUE TITLE
Package unavailable for task

### ISSUE THREAD

**Issue by lizhuoyuan** [roughike/flutter_facebook_login#88]
Package unavailable for task: com.shopee.sg/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="DataPointService" trigger=window{start=0s,end=7200s,earliest=-5518114s,latest=-5510914s} requirements=[NET_CONNECTED,CHARGING] attributes=[PERSISTED,RECURRING] scheduled=-5518114s last_run=N/A jid=N/A status=PENDING retries=0 client_lib=FIREBASE_JOB_DISPATCHER-1}

**Comment by roughike** [comment]
Doesn't seem related to this library, right? Feel free to provide more info if otherwise, and I'll reopen.
