### ISSUE TITLE
The AndroidX PR of this library isn't compatible with firebase_messaging 3.0.1

### ISSUE THREAD

**Issue by trey-rosius** [roughike/flutter_facebook_login#95]
Hi,
My Application was working fine, until i upgraded all it's libraries to their AndroidX supported versions. 
Then i encountered a strange issue between the firebase messaging plugin and flutter facebook plugin. When you use both in same project, the app closes immediately on startup, and throws this exception 
`Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65296/ws. `
But when you take one off, the app runs well. I don't know what the issue might be, but judging for this https://stackoverflow.com/questions/49949818/firebaseinstanceid-token-retrieval-failed-service-not-available/50517006, maybe it's the facebook version.
Is Anybody facing this same issue?

**Comment by gi097** [comment]
Maybe you can try mine? #96

**Comment by roughike** [comment]
@trey-rosius can you try @gi097's fix using instructions described here: https://github.com/roughike/flutter_facebook_login/issues/85#issuecomment-466637308 ?

**Comment by trey-rosius** [comment]
@roughike . Works Perfectly now. Thanks a lot

**Comment by roughike** [comment]
Thanks for confirming - I'll release 2.0 on Pub after a couple days once I get some confirmations that it works for others as well.
